import os
from playsound import playsound
import datetime

extracted_time = open("B:\\Jarvis 4 (Without GUI)\\Back\\Data.txt",'rt')
time = extracted_time.read()
Time = str(time)
delete_time = open('B:\\Jarvis 4 (Without GUI)\\Back\\Data.txt','r+')
delete_time.truncate(0)
delete_time.close()
# print(time)

def RingNow(time):
    time_to_set = str(time)
    # time_now = time_to_set.replace("jarvis",'')
    # time_now = time_now.replace('set alarm for ','')
    # time_now = time_now.replace('set ','')
    # time_now = time_now.replace('alarm ','')
    # time_now = time_now.replace('for ','')
    # time_now = time_now.replace(' and ',':')

    Alarm_time = str(time_to_set)
    while True:
                current_time = datetime.datetime.now().strftime("%H:%M")
                if current_time == Alarm_time:
                    import webbrowser
                    webbrowser.open("https://www.youtube.com/")
                    import Back.application
                    Back.application.close_chrome()
                    Back.application.open_M()
                    Back.application.close_M()
                    Back.application.open_Blue()
                    Back.application.close_Blue()
                    import pyautogui
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    pyautogui.press("volumeup")
                    import random
                    import os
                    s3 = ['B:\\Jarvis 4 (Without GUI)\\Alarm Music\\M1.wav','B:\\Jarvis 4 (Without GUI)\\Alarm Music\\M2.wav']
                    s4 = ['B:\\Jarvis 4 (Without GUI)\\Alarm Music\\M3.wav','B:\\Jarvis 4 (Without GUI)\\Alarm Music\\M4.wav']
                    s5 = ['B:\\Jarvis 4 (Without GUI)\\Alarm Music\\M1.wav','B:\\Jarvis 4 (Without GUI)\\Alarm Music\\M6.wav']
                    s6 = ['B:\\Jarvis 4 (Without GUI)\\Alarm Music\\M7.wav','B:\\Jarvis 4 (Without GUI)\\Alarm Music\\M8.wav']
                    s7 = random.choice(s3)
                    s8 = random.choice(s4)
                    s9 = random.choice(s5)
                    s10 = random.choice(s6)
                    print(" ")
                    print("I Am Playing :",s7)
                    print(" ")
                    print("I Am Playing :",s8)
                    print(" ")
                    print("I Am Playing :",s9)
                    print(" ")
                    print("I Am Playing :",s10)
                    print(" ")
                    playsound(s7)
                    playsound(s8)
                    playsound(s9)
                    playsound(s10)
                elif current_time>Alarm_time:
                    import pyautogui
                    from speak import speak_only
                    speak_only("Alarm Is CLosed")
                    speak_only("Wake Up Sir Or I Will Call Your Mom Or Dad ")
                    speak_only("Wake Up Sir Or I Will Call Your Mom Or Dad ")
                    speak_only("Wake Up Sir Or I Will Call Your Mom Or Dad ")
                    speak_only("Wake Up Sir Or I Will Call Your Mom Or Dad ")
                    speak_only("Wake Up Sir Or I Will Call Your Mom Or Dad ")
                    speak_only("Wake Up Sir Or I Will Call Your Mom Or Dad ")
                    speak_only("Wake Up Sir Or I Will Call Your Mom Or Dad ")
                    speak_only("Wake Up Sir Or I Will Call Your Mom Or Dad ")
                    import pyautogui
                    pyautogui.press("volumedown")
                    
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    pyautogui.press("volumedown")
                    break   