# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1907, 1036)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BG_2 = QtWidgets.QLabel(self.centralwidget)
        self.BG_2.setGeometry(QtCore.QRect(20, 10, 651, 501))
        self.BG_2.setStyleSheet("background-color: rgb(0, 230, 230);")
        self.BG_2.setText("")
        self.BG_2.setObjectName("BG_2")
        self.BG_3 = QtWidgets.QLabel(self.centralwidget)
        self.BG_3.setGeometry(QtCore.QRect(690, 10, 661, 501))
        self.BG_3.setStyleSheet("background-color: rgb(0, 230, 230);")
        self.BG_3.setText("")
        self.BG_3.setObjectName("BG_3")
        self.GIF_1 = QtWidgets.QLabel(self.centralwidget)
        self.GIF_1.setGeometry(QtCore.QRect(30, 20, 631, 481))
        self.GIF_1.setText("")
        self.GIF_1.setPixmap(QtGui.QPixmap("GUI/B.G/Iron_Template_1.gif"))
        self.GIF_1.setScaledContents(True)
        self.GIF_1.setObjectName("GIF_1")
        self.GIF_2 = QtWidgets.QLabel(self.centralwidget)
        self.GIF_2.setGeometry(QtCore.QRect(700, 20, 641, 481))
        self.GIF_2.setText("")
        self.GIF_2.setPixmap(QtGui.QPixmap("GUI/ExtraGui/live.gif"))
        self.GIF_2.setScaledContents(True)
        self.GIF_2.setObjectName("GIF_2")
        self.GIF_4 = QtWidgets.QLabel(self.centralwidget)
        self.GIF_4.setGeometry(QtCore.QRect(-160, 430, 821, 621))
        self.GIF_4.setText("")
        self.GIF_4.setPixmap(QtGui.QPixmap("GUI/VoiceReg/__1.gif"))
        self.GIF_4.setScaledContents(True)
        self.GIF_4.setObjectName("GIF_4")
        self.BG_1 = QtWidgets.QLabel(self.centralwidget)
        self.BG_1.setGeometry(QtCore.QRect(-990, -390, 3391, 1471))
        self.BG_1.setText("")
        self.BG_1.setPixmap(QtGui.QPixmap("GUI/B.G/Black_Template.jpg"))
        self.BG_1.setScaledContents(True)
        self.BG_1.setObjectName("BG_1")
        self.BG_4 = QtWidgets.QLabel(self.centralwidget)
        self.BG_4.setGeometry(QtCore.QRect(1370, 10, 521, 371))
        self.BG_4.setStyleSheet("background-color: rgb(0, 230, 230);")
        self.BG_4.setText("")
        self.BG_4.setObjectName("BG_4")
        self.GIF_3 = QtWidgets.QLabel(self.centralwidget)
        self.GIF_3.setGeometry(QtCore.QRect(1380, 20, 501, 351))
        self.GIF_3.setText("")
        self.GIF_3.setPixmap(QtGui.QPixmap("GUI/ExtraGui/Earth.gif"))
        self.GIF_3.setScaledContents(True)
        self.GIF_3.setObjectName("GIF_3")
        self.BG_5 = QtWidgets.QLabel(self.centralwidget)
        self.BG_5.setGeometry(QtCore.QRect(1380, 880, 521, 151))
        self.BG_5.setText("")
        self.BG_5.setPixmap(QtGui.QPixmap("GUI/B.G/gggf.jpg"))
        self.BG_5.setScaledContents(True)
        self.BG_5.setObjectName("BG_5")
        self.BG_6 = QtWidgets.QLabel(self.centralwidget)
        self.BG_6.setGeometry(QtCore.QRect(1380, 730, 521, 151))
        self.BG_6.setText("")
        self.BG_6.setPixmap(QtGui.QPixmap("GUI/B.G/gggf.jpg"))
        self.BG_6.setScaledContents(True)
        self.BG_6.setObjectName("BG_6")
        self.BG_7 = QtWidgets.QLabel(self.centralwidget)
        self.BG_7.setGeometry(QtCore.QRect(1380, 570, 511, 161))
        self.BG_7.setText("")
        self.BG_7.setPixmap(QtGui.QPixmap("GUI/B.G/gggf.jpg"))
        self.BG_7.setScaledContents(True)
        self.BG_7.setObjectName("BG_7")
        self.Text_Day = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Day.setGeometry(QtCore.QRect(1440, 770, 421, 71))
        self.Text_Day.setStyleSheet("background-color:Transparent;\n"
"border-radius:none;\n"
"color: rgb(0, 168, 168);\n"
"font: 22pt \"Microsoft Sans Serif\";")
        self.Text_Day.setObjectName("Text_Day")
        self.Text_Date = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Date.setGeometry(QtCore.QRect(1435, 625, 425, 75))
        # self.Text_Date.setGeometry(QtCore.QRect(1430, 620, 421, 71))
        self.Text_Date.setStyleSheet("background-color:Transparent;\n"
"border-radius:none;\n"
"color: rgb(0, 168, 168);\n"
"font: 22pt \"Microsoft Sans Serif\";")
        self.Text_Date.setObjectName("Text_Date")
        self.Text_Time = QtWidgets.QTextBrowser(self.centralwidget)
        # self.Text_Time.setGeometry(QtCore.QRect(1445, 925, 435, 175))
        self.Text_Time.setGeometry(QtCore.QRect(1440, 920, 4214, 7145))
        # self.Text_Time.setGeometry(QtCore.QRect(1440, 920, 421, 71))
        self.Text_Time.setStyleSheet("background-color:Transparent;\n"
"border-radius:none;\n"
"color: rgb(0, 168, 168);"
"font: 22pt \"Microsoft Sans Serif\";")
        self.Text_Time.setObjectName("Text_Time")
        self.BG_8 = QtWidgets.QLabel(self.centralwidget)
        self.BG_8.setGeometry(QtCore.QRect(1370, 390, 521, 171))
        self.BG_8.setStyleSheet("background-color: rgb(0, 230, 230);")
        self.BG_8.setText("")
        self.BG_8.setObjectName("BG_8")
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setGeometry(QtCore.QRect(1380, 400, 501, 71))
        self.pushButton_Start.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 255, 0);\n"
"font: 22pt \"Microsoft Sans Serif\";")
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.pushButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Stop.setGeometry(QtCore.QRect(1380, 480, 501, 71))
        self.pushButton_Stop.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Microsoft Sans Serif\";\n"
"background-color: REd;")
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.pushButton_VS = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_VS.setGeometry(QtCore.QRect(1190, 520, 161, 61))
        self.pushButton_VS.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"font: 75 italic 22pt \"Segoe UI\";")
        self.pushButton_VS.setObjectName("pushButton_VS")
        self.pushButton_Chrome = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Chrome.setGeometry(QtCore.QRect(1020, 520, 161, 61))
        self.pushButton_Chrome.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"font: 75 italic 22pt \"Segoe UI\";")
        self.pushButton_Chrome.setObjectName("pushButton_Chrome")
        self.pushButton_Youtube = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Youtube.setGeometry(QtCore.QRect(850, 520, 161, 61))
        self.pushButton_Youtube.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"font: 75 italic 22pt \"Segoe UI\";")
        self.pushButton_Youtube.setObjectName("pushButton_Youtube")
        self.BG_1.raise_()
        self.GIF_4.raise_()
        self.BG_2.raise_()
        self.BG_3.raise_()
        self.GIF_1.raise_()
        self.GIF_2.raise_()
        self.BG_4.raise_()
        self.GIF_3.raise_()
        self.BG_6.raise_()
        self.BG_7.raise_()
        self.Text_Day.raise_()
        self.Text_Date.raise_()
        self.BG_5.raise_()
        self.Text_Time.raise_()
        self.BG_8.raise_()
        self.pushButton_Start.raise_()
        self.pushButton_Stop.raise_()
        self.pushButton_VS.raise_()
        self.pushButton_Chrome.raise_()
        self.pushButton_Youtube.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Start.setText(_translate("MainWindow", "START"))
        self.pushButton_Stop.setText(_translate("MainWindow", "STOP"))
        self.pushButton_VS.setText(_translate("MainWindow", "VS Code"))
        self.pushButton_Chrome.setText(_translate("MainWindow", "Chrome"))
        self.pushButton_Youtube.setText(_translate("MainWindow", "YouTube"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
